cp xlarge.txt inf1.txt &
cp xlarge.txt inf2.txt &
cp xlarge.txt inf3.txt &
cp xlarge.txt inf4.txt &
cp xlarge.txt inf5.txt &
cp xlarge.txt inf6.txt &
cp xlarge.txt inf7.txt &
cp xlarge.txt inf8.txt &
cp xlarge.txt inf9.txt &
cp xlarge.txt inf10.txt &
cp xlarge.txt inf11.txt &
cp xlarge.txt inf12.txt &
cp xlarge.txt inf13.txt &
cp xlarge.txt inf14.txt &
cp xlarge.txt inf15.txt &
cp xlarge.txt inf16.txt &
cp xlarge.txt inf17.txt &
